name: UW-CS484-final-project
channels:
  - defaults
  - pytorch
dependencies:
  - jupyter=1.0.0
  - jupyterlab=3.4.4
  - matplotlib=3.6.2
  - numpy=1.23.4
  - pandas=1.5.2
  - pillow=9.2.0
  - python=3.9.15
  - pytorch=1.13.1
  - torchvision=0.14.1
  - tqdm=4.64.1